config/routes.rb
Rails.application.routes.draw do
  root 'events#index'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  resources :users, only: [:show]
  resources :events, only: [:show, :new, :create]
  resources :attendences, only: [:create, :destroy]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendence.rb
class Attendence < ApplicationRecord
  belongs_to :attendee, foreign_key: :attendee_id, class_name: 'User'
  belongs_to :attended_event, foreign_key: :attended_event_id, class_name: 'Event'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, foreign_key: :creator_id, class_name: 'User'
  has_many :attendences, foreign_key: :attended_event_id, dependent: :destroy
  has_many :attendees, through: :attendences

  scope :previous, -> { Event.all.where('date <= ?', Time.zone.now.beginning_of_day).order(date: :DESC) }
  scope :upcoming, -> { Event.all.where('date > ?', Time.zone.now.beginning_of_day).order(:date) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :events, foreign_key: :creator_id, dependent: :destroy
  has_many :attendences, foreign_key: :attendee_id, dependent: :destroy
  has_many :attended_events, through: :attendences
  has_secure_password

  def is_attending?(event_id)
    attended_events.exists?(event_id)
  end

  def previous_events
    events.where('date <= ?', Time.zone.now.beginning_of_day).order(date: :DESC)
  end

  def upcoming_events
    events.where('date > ?', Time.zone.now.beginning_of_day).order(:date)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper
end

app/controllers/attendences_controller.rb
class AttendencesController < ApplicationController

  def create
    @attendence = current_user.attendences.build(attendence_params)
    @attendence.save
    redirect_to @attendence.attended_event
  end

  def destroy
    @attendence = current_user.attendences.find_by(attended_event_id: params[:attendence][:attended_event_id])
    @event = @attendence.attended_event
    @attendence.destroy
    redirect_to @event
  end

  private
    def attendence_params
      params.require(:attendence).permit(:attended_event_id)
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.events.build(event_params)
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  private
    def event_params
      params.require(:event).permit(:name, :location, :date)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new

  end

  def create
    @user = User.find_by(email: params[:session][:email])
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendences_helper.rb
module AttendencesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    if user_id = session[:user_id]
      @current_user ||= User.find_by(id: user_id)
    end
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<%= link_to(event) do %>
  <div>
    <h4><%= event.name %></h4>
    <p><%= event.date.strftime("%B %d, %Y") %></p>
  <div>
<% end %>
<hr>

app/views/events/index.html.erb
<h2>Upcoming events:</h2>
<%= render Event.upcoming %>
<h2>Previous events:</h2>
<%= render Event.previous %>

app/views/events/new.html.erb
<h1>New event</h1>
<%= form_for(@event) do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :location %><br>
  <%= f.text_field :location %><br>
  <%= f.label :date %><br>
  <%= f.date_select(:date, order: [:month, :day, :year]) %><br>
  <%= f.submit "Submit" %>
<% end %>

app/views/events/show.html.erb
<h2><%= @event.name %></h2>
<ul>
  <li>Host: <%= link_to @event.creator.name, @event.creator %></li>
  <li>Location: <%= @event.location %></li>
  <li>Date: <%= @event.date.strftime("%B %d, %Y") %></li>
</ul>
<% if current_user.is_attending? @event.id %>
  <%= form_for(:attendence, url: attendence_path, method: 'delete') do |f| %>
    <%= f.hidden_field :attended_event_id, value: @event.id %>
    <%= f.submit "Unattend" %>
  <% end %>
<% else %>
  <%= form_for(:attendence, url: attendences_path, method: 'post') do |f| %>
    <%= f.hidden_field :attended_event_id, value: @event.id %>
    <%= f.submit "Attend" %>
  <% end %>
<% end %>
<h3>Attendees:</h3>
<ul>
  <% @event.attendees.each do |attendee| %>
    <li><%= attendee.name %></li>
  <% end %>
</ul>

app/views/layouts/_header.html.erb
<header>
  <nav>
    <%= link_to "Home", root_path %>
    <% if current_user %>
      <%= link_to "New event", new_event_path %>
      <%= link_to "Profile", current_user %>
      <%= link_to "Log out", logout_path, method: 'delete' %>
      <span>(<%= current_user.name %>)</span>
    <% else %>
      <%= link_to "Sign up", signup_path %>
      <%= link_to "Log in", login_path %>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>New User</h1>
<%= form_for(@user, url: signup_path) do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :email %><br>
  <%= f.text_field :email %><br>
  <%= f.label :password %><br>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit "Submit" %>
<% end %>

app/views/users/show.html.erb
<h1>Hi <%= @user.name %></h1>
<h2>Upcoming events:</h2>
<%= render @user.upcoming_events %>
<h2>Previous events:</h2>
<%= render @user.previous_events %>